# This is a basic workflow to help you get started with Actions

name: testAbuse

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out this repo
      uses: actions/checkout@v2
    #
    - name: Run a one-line script
      env:
         MALSHARE_API: ${{ secrets.MALSHARE_API }}
         VAR1: Hola
         VAR2: Nuria
      run: |
         echo $MALSHARE_API
         echo $VAR1 $VAR2
      #run:  wget https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt -O abuse-ch/ipblocklist_recommended-ips.txt
      #with:
         #config: download-feeds.yml
         #configSection: abuse_sh
    # commit
    - name: Commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git status
        git add -A
        git status
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        
    - name: Push
      if: steps.check_changes.outputs.bigChange != 'true'
      run: |-
        git push
 
    #- name: Create PR
      #if: steps.check_changes.outputs.bigChange == 'true'
      #uses: peter-evans/create-pull-request@v3.6.0
      #with:
        #branch: please-check-changes
